export const SUBMIT_ERROR_MODAL_SHOW = "SUBMIT_ERROR_MODAL_SHOW";
export const SUBMIT_ERROR_MODAL_CLOSE = "SUBMIT_ERROR_MODAL_CLOSE";

export const CONFIRM_SUBMIT_MODAL_SHOW = "CONFIRM_SUBMIT_MODAL_SHOW";
export const CONFIRM_SUBMIT_MODAL_CLOSE = "CONFIRM_SUBMIT_MODAL_CLOSE";
