export const SHOW_TEAMS = "SHOW_TEAMS";
export const SHOW_CUSTOM_TEAMS = "SHOW_CUSTOM_TEAMS";
export const CUSTOM_TEAM_CREATE = "CUSTOM_TEAM_CREATE";
export const CUSTOM_TEAM_DELETE = "CUSTOM_TEAM_DELETE";
