export const USER_DATA_SHOW = "USER_DATA_SHOW";
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";
export const USER_INDUSTRY_UPDATE = "USER_INDUSTRY_UPDATE";
export const USER_COMPANY_UPDATE = "USER_COMPANY_UPDATE";
export const USER_BILLINGS_UPDATE = "USER_BILLINGS_UPDATE";
export const EDUCATION_CARD_WITH_ID_EDIT = "EDUCATION_CARD_WITH_ID_EDIT";
export const EXPERIENCE_CARD_WITH_ID_EDIT = "EXPERIENCE_CARD_WITH_ID_EDIT";
