export const SHOW_EPIC_TASKS = "SHOW_EPIC_TASKS";
export const SHOW_SPECIALIST_TASKS = "SHOW_SPECIALIST_TASKS";
export const EPIC_TASK_CREATE = "EPIC_TASK_CREATE";
export const EPIC_TASK_DELETE = "EPIC_TASK_DELETE";
